name: CI Pipeline

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
    - uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push combined image
      run: |
        docker build -t Wayssm/Phanex:latest .
        docker push Wayssm/Phanex:latest
    - name: Deploy combined Container
      run: |
        docker pull Wayssm/Phanex:latest
        docker stop Phanex || true
        docker rm Phanex || true
        docker run -d --name Phanex -p 8080:8080 Wayssm/Phanex:latest
